<?php
/**
 * File to load generated classes once at once time
 * @package LogicMelon
 * @date 2014-09-22
 * @author Mikaël DELSOL
 * @version 1
 */
/**
 * Includes for all generated classes files
 * @date 2014-09-22
 * @author Mikaël DELSOL
 * @version 1
 */
require_once dirname(__FILE__) . '/LogicMelonWsdlClass.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructMpats_PostJob_TrackResult.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructArrayOfInt.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructValidateAdvertResult.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructValidateAdvertValuesResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructValidateAdvertValues.php';
require_once dirname(__FILE__) . '/Enum/LogicMelonEnumValidateAdvertValid.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructArrayOfValidateFieldResult.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructUserFeedsAndQuota.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructUserFeedsAndQuotaResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructDeliverAdvertResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructDeliverAdvert.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructValidateFieldResult.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAddAdvertValuesResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAddAdvertWithValuesResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructUnarchiveAdvertResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructUnarchiveAdvertWithFilters.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructUnarchiveAdvert.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructArchiveAdvertWithFiltersResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructArchiveAdvertWithFilters.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructUnarchiveAdvertWithFiltersResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAddAdvert.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructArrayOfCPostFeed.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAddAdvertWithValues.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAddAdvertResult.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAddAdvertResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAddAdvertValues.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructCPostFeed.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructQueryJobTitle.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructQueryJobTitleResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructCQueryLocation.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructArrayOfCQueryLocation.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructQueryLocationsResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructArrayOfCQueryJobTitle.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructCQueryJobTitle.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAddAdvertCandidateWithFiltersResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAddAdvertCandidateWithFilters.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAddAdvertCandidateResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAddAdvertCandidate.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructQueryLocations.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetCurrencyResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructExpressPostAdvertResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructExpressPostAdvertWithFilters.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructExpressPostAdvert.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructUserFeedsAndQuotaWithDestinationsResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructUserFeedsAndQuotaWithDestinations.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructExpressPostAdvertWithFiltersResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetValues.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetCurrency.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetValue.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructArrayOfGetValue.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetValuesResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructArchiveAdvertResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructArchiveAdvert.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAPIAdvertPaged.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructArrayOfAPIAdvert.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetAdvertPagedResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetAdvertPaged.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetApplicationsWithFiltersResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAPIAdvert.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetAdvert.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetAdvertWithFilters.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetAdvertWithFiltersPagedResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetAdvertWithFiltersPaged.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetAdvertResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetApplicationsWithFilters.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetApplicationsWithFiltersPagedResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAPIApplication.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAPIApplicationAttachment.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructArrayOfAPIApplication.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAPIApplicationPaged.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetApplicationsPagedResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetApplications.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetApplicationsResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructNameValue.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructArrayOfNameValue.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructArrayOfString.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetApplicationsWithFiltersPaged.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetAdvertWithFiltersResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetAdvertWithValues.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructArrayOfAPIPosting.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAPIPosting.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAPIAdvertWithPostings.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructArrayOfAPIAdvertWithPostings.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructTrackAdvertResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructTrackAdvertWithFilters.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructTrackAdvertWithFiltersResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructCloseAdvertWithFiltersResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructCloseAdvertWithFilters.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructCloseAdvertResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructCloseAdvert.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructTrackAdvert.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetAdvertWithValuesWithFiltersPagedResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructArrayOfAPIAdvertValue.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAPIAdvertValue.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAPIAdvertWithValues.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructArrayOfAPIAdvertWithValues.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetAdvertWithValuesResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetAdvertWithValuesPaged.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetAdvertWithValuesPagedResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetAdvertWithValuesWithFiltersPaged.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetAdvertWithValuesWithFiltersResponse.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetAdvertWithValuesWithFilters.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructAPIAdvertWithValuesPaged.php';
require_once dirname(__FILE__) . '/Struct/LogicMelonStructGetApplicationsPaged.php';
require_once dirname(__FILE__) . '/Service/LogicMelonServiceGet.php';
require_once dirname(__FILE__) . '/Service/LogicMelonServiceTrack.php';
require_once dirname(__FILE__) . '/Service/LogicMelonServiceClose.php';
require_once dirname(__FILE__) . '/Service/LogicMelonServiceArchive.php';
require_once dirname(__FILE__) . '/Service/LogicMelonServiceUnarchive.php';
require_once dirname(__FILE__) . '/Service/LogicMelonServiceAdd.php';
require_once dirname(__FILE__) . '/Service/LogicMelonServiceValidate.php';
require_once dirname(__FILE__) . '/Service/LogicMelonServiceDeliver.php';
require_once dirname(__FILE__) . '/Service/LogicMelonServiceUser.php';
require_once dirname(__FILE__) . '/Service/LogicMelonServiceExpress.php';
require_once dirname(__FILE__) . '/Service/LogicMelonServiceQuery.php';
require_once dirname(__FILE__) . '/LogicMelonClassMap.php';
