<?php
/**
 * File for the class which returns the class map definition
 * @package LRS
 * @author WsdlToPhp Team <contact@wsdltophp.com>
 * @version 20150429-01
 * @date 2017-08-18
 */
/**
 * Class which returns the class map definition by the static method LRSClassMap::classMap()
 * @package LRS
 * @author WsdlToPhp Team <contact@wsdltophp.com>
 * @version 20150429-01
 * @date 2017-08-18
 */
class LRSClassMap
{
    /**
     * This method returns the array containing the mapping between WSDL structs and generated classes
     * This array is sent to the SoapClient when calling the WS
     * @return array
     */
    final public static function classMap()
    {
        return array (
  'AbilityToShare' => 'LRSEnumAbilityToShare',
  'AchievementStatus' => 'LRSEnumAchievementStatus',
  'ArrayOfAwardingOrganisation' => 'LRSStructArrayOfAwardingOrganisation',
  'ArrayOfBarredUnit' => 'LRSStructArrayOfBarredUnit',
  'ArrayOfGroup' => 'LRSStructArrayOfGroup',
  'ArrayOfLearnerEvent' => 'LRSStructArrayOfLearnerEvent',
  'ArrayOfLearningEvent' => 'LRSStructArrayOfLearningEvent',
  'ArrayOfLinkedNQFUnit' => 'LRSStructArrayOfLinkedNQFUnit',
  'ArrayOfLinkedUnit' => 'LRSStructArrayOfLinkedUnit',
  'ArrayOfListDataChallengeItem' => 'LRSStructArrayOfListDataChallengeItem',
  'ArrayOfNQFGroup' => 'LRSStructArrayOfNQFGroup',
  'ArrayOfNQFUnit' => 'LRSStructArrayOfNQFUnit',
  'ArrayOfPlrAccessEntryResponse' => 'LRSStructArrayOfPlrAccessEntryResponse',
  'ArrayOfPlrSnapshotEvent' => 'LRSStructArrayOfPlrSnapshotEvent',
  'ArrayOfRocQueryResultGroup' => 'LRSStructArrayOfRocQueryResultGroup',
  'ArrayOfRocQueryResultUnit' => 'LRSStructArrayOfRocQueryResultUnit',
  'ArrayOfRtaOneQuery' => 'LRSStructArrayOfRtaOneQuery',
  'ArrayOfRtaOneQueryResult' => 'LRSStructArrayOfRtaOneQueryResult',
  'ArrayOfSectorSubjectArea' => 'LRSStructArrayOfSectorSubjectArea',
  'ArrayOfSnapshot' => 'LRSStructArrayOfSnapshot',
  'ArrayOfSnapshotEvent' => 'LRSStructArrayOfSnapshotEvent',
  'ArrayOfUnit' => 'LRSStructArrayOfUnit',
  'ArrayOfUpdateLearnerResponseItem' => 'LRSStructArrayOfUpdateLearnerResponseItem',
  'ArrayOfstring' => 'LRSStructArrayOfstring',
  'AwardingOrganisation' => 'LRSStructAwardingOrganisation',
  'AwardingOrganisationStatus' => 'LRSEnumAwardingOrganisationStatus',
  'BarredNQFUnit' => 'LRSStructBarredNQFUnit',
  'BarredUnit' => 'LRSStructBarredUnit',
  'BarredUnitBase' => 'LRSStructBarredUnitBase',
  'BusinessObject' => 'LRSStructBusinessObject',
  'Channel' => 'LRSEnumChannel',
  'ChildManagedBusinessObject' => 'LRSStructChildManagedBusinessObject',
  'CompoundGroup' => 'LRSStructCompoundGroup',
  'CreateDataChallenge' => 'LRSStructCreateDataChallenge',
  'CreateDataChallengeResponse' => 'LRSStructCreateDataChallengeResponse',
  'CreateLearnerKeyResponse' => 'LRSStructCreateLearnerKeyResponse',
  'CreateOrModifySnapshot' => 'LRSStructCreateOrModifySnapshot',
  'CreateOrModifySnapshotResponse' => 'LRSStructCreateOrModifySnapshotResponse',
  'DeleteDataChallenge' => 'LRSStructDeleteDataChallenge',
  'DeleteDataChallengeResponse' => 'LRSStructDeleteDataChallengeResponse',
  'DeleteLearnerKeyResponse' => 'LRSStructDeleteLearnerKeyResponse',
  'DeleteSavedRtaQuery' => 'LRSStructDeleteSavedRtaQuery',
  'DeleteSavedRtaQueryResponse' => 'LRSStructDeleteSavedRtaQueryResponse',
  'DeleteSnapshot' => 'LRSStructDeleteSnapshot',
  'DeleteSnapshotResponse' => 'LRSStructDeleteSnapshotResponse',
  'DomainFault' => 'LRSStructDomainFault',
  'ExecuteRoCQuery' => 'LRSStructExecuteRoCQuery',
  'ExecuteRoCQueryResponse' => 'LRSStructExecuteRoCQueryResponse',
  'ExecuteRtaQuery' => 'LRSStructExecuteRtaQuery',
  'ExecuteRtaQueryResponse' => 'LRSStructExecuteRtaQueryResponse',
  'ExecuteRtaResponse' => 'LRSStructExecuteRtaResponse',
  'FindLearnerByUlnKey' => 'LRSStructFindLearnerByUlnKey',
  'FindLearnerByUlnKeyResponse' => 'LRSStructFindLearnerByUlnKeyResponse',
  'Gender' => 'LRSEnumGender',
  'GetLearnerLearningEvents' => 'LRSStructGetLearnerLearningEvents',
  'GetLearnerLearningEventsResponse' => 'LRSStructGetLearnerLearningEventsResponse',
  'GetLearnerRecord' => 'LRSStructGetLearnerRecord',
  'GetLearnerRecordResponse' => 'LRSStructGetLearnerRecordResponse',
  'GetMyLearningEvents' => 'LRSStructGetMyLearningEvents',
  'GetMyLearningEventsResponse' => 'LRSStructGetMyLearningEventsResponse',
  'GetOrganisation' => 'LRSStructGetOrganisation',
  'GetOrganisationResponse' => 'LRSStructGetOrganisationResponse',
  'GradingStructure' => 'LRSStructGradingStructure',
  'Group' => 'LRSStructGroup',
  'GroupBase' => 'LRSStructGroupBase',
  'InvokingOrganisation' => 'LRSStructInvokingOrganisation',
  'InvokingOrganisationR10' => 'LRSStructInvokingOrganisationR10',
  'Learner' => 'LRSStructLearner',
  'LearnerByUln' => 'LRSStructLearnerByUln',
  'LearnerByUlnKeyResponse' => 'LRSStructLearnerByUlnKeyResponse',
  'LearnerByUlnResponse' => 'LRSStructLearnerByUlnResponse',
  'LearnerEvent' => 'LRSStructLearnerEvent',
  'LearningEvent' => 'LRSStructLearningEvent',
  'Level' => 'LRSStructLevel',
  'LinkedNQFUnit' => 'LRSStructLinkedNQFUnit',
  'LinkedUnit' => 'LRSStructLinkedUnit',
  'ListDataChallenge' => 'LRSStructListDataChallenge',
  'ListDataChallengeItem' => 'LRSStructListDataChallengeItem',
  'ListDataChallengeResponse' => 'LRSStructListDataChallengeResponse',
  'ListNotificationStatus' => 'LRSStructListNotificationStatus',
  'ListNotificationStatusResponse' => 'LRSStructListNotificationStatusResponse',
  'ListSavedRtaQueries' => 'LRSStructListSavedRtaQueries',
  'ListSavedRtaQueriesResponse' => 'LRSStructListSavedRtaQueriesResponse',
  'ListSnapshotResponse' => 'LRSStructListSnapshotResponse',
  'ListSnapshots' => 'LRSStructListSnapshots',
  'ListSnapshotsResponse' => 'LRSStructListSnapshotsResponse',
  'ManagedBusinessObject' => 'LRSStructManagedBusinessObject',
  'NQFCompoundGroup' => 'LRSStructNQFCompoundGroup',
  'NQFGroup' => 'LRSStructNQFGroup',
  'NQFOtherCreditGroup' => 'LRSStructNQFOtherCreditGroup',
  'NQFUnit' => 'LRSStructNQFUnit',
  'NQFUnitGroup' => 'LRSStructNQFUnitGroup',
  'NotificationPreference' => 'LRSEnumNotificationPreference',
  'OtherCreditGroup' => 'LRSStructOtherCreditGroup',
  'PagedListOfPlrAccessEntryResponseN4dIIFC_S' => 'LRSStructPagedListOfPlrAccessEntryResponseN4dIIFC_S',
  'PersistedBusinessObject' => 'LRSStructPersistedBusinessObject',
  'PlrAccessEntryResponse' => 'LRSStructPlrAccessEntryResponse',
  'PlrSnapshotEvent' => 'LRSStructPlrSnapshotEvent',
  'Qualification' => 'LRSStructQualification',
  'QualificationLevel' => 'LRSStructQualificationLevel',
  'QualificationSubLevel' => 'LRSStructQualificationSubLevel',
  'RemoveLearnerKey' => 'LRSStructRemoveLearnerKey',
  'RemoveLearnerKeyResponse' => 'LRSStructRemoveLearnerKeyResponse',
  'ReplicatedBusinessObject' => 'LRSStructReplicatedBusinessObject',
  'RocQueryResult' => 'LRSStructRocQueryResult',
  'RocQueryResultGroup' => 'LRSStructRocQueryResultGroup',
  'RocQueryResultUnit' => 'LRSStructRocQueryResultUnit',
  'RtaListResponse' => 'LRSStructRtaListResponse',
  'RtaOneQuery' => 'LRSStructRtaOneQuery',
  'RtaOneQueryResult' => 'LRSStructRtaOneQueryResult',
  'SaveRtaQuery' => 'LRSStructSaveRtaQuery',
  'SaveRtaQueryResponse' => 'LRSStructSaveRtaQueryResponse',
  'SectorSubjectArea' => 'LRSStructSectorSubjectArea',
  'ServiceResponseR9' => 'LRSStructServiceResponseR9',
  'SetNotification' => 'LRSStructSetNotification',
  'SetNotificationResponse' => 'LRSStructSetNotificationResponse',
  'Snapshot' => 'LRSStructSnapshot',
  'SnapshotEvent' => 'LRSStructSnapshotEvent',
  'StoreLearnerKey' => 'LRSStructStoreLearnerKey',
  'StoreLearnerKeyResponse' => 'LRSStructStoreLearnerKeyResponse',
  'Structure' => 'LRSStructStructure',
  'Unit' => 'LRSStructUnit',
  'UnitAvailability' => 'LRSEnumUnitAvailability',
  'UnitBase' => 'LRSStructUnitBase',
  'UnitGradingStructure' => 'LRSEnumUnitGradingStructure',
  'UnitGroup' => 'LRSStructUnitGroup',
  'UnitStatus' => 'LRSEnumUnitStatus',
  'UpdateLearner' => 'LRSStructUpdateLearner',
  'UpdateLearnerByUlnKey' => 'LRSStructUpdateLearnerByUlnKey',
  'UpdateLearnerByUlnKeyResponse' => 'LRSStructUpdateLearnerByUlnKeyResponse',
  'UpdateLearnerResponse' => 'LRSStructUpdateLearnerResponse',
  'UpdateLearnerResponseItem' => 'LRSStructUpdateLearnerResponseItem',
  'UpdateLearnerSubsetFields' => 'LRSStructUpdateLearnerSubsetFields',
  'UpdateLearnerSubsetFieldsResponse' => 'LRSStructUpdateLearnerSubsetFieldsResponse',
  'UserType' => 'LRSEnumUserType',
  'ViewAudit' => 'LRSStructViewAudit',
  'ViewAuditResponse' => 'LRSStructViewAuditResponse',
);
    }
}
